---
test:
  name: simple
  description:
    This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 5
  rounds:
    - label: open
      description: Test description for the opening of an account through the deployed chaincode
      txDuration:
        - 15
      trim: 5
      rateControl:
        - type: fixed-rate
          opts:
            tps: 130
      arguments:
        money: 100000
      callback: benchmark/simple/open.js
    - label: query
      description: Test description for the query performance of the deployed chaincode
      trim: 5
      txDuration:
        - 15
      rateControl:
        - type: fixed-rate
          opts:
            tps: 130
      callback: benchmark/simple/query.js
monitor:
  type:
    - docker
  docker:
    name:
      - all
  interval: 1
